version: '3'

volumes:
  amsdata:
    external: true

services:

  http-hosting:
    image: "${IMAGE_AMS}"
    environment:
      IMAGE_AMS: "${IMAGE_AMS}"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    command: >
        /usr/bin/docker-compose
          -f /http/docker-compose.yml
          up

  fwc-cam1:
    image: "${IMAGE_AMS}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      IMAGE_AMS: "${IMAGE_AMS}"
      SW_OR_HW: "${SW_OR_HW}"
      CAMERA_URI: /sample/coral.mp4
      CORAL_SPAWN_PREDICT_ENDPOINT: http://coral-spawn-service.local/predict
    command: >
      /usr/bin/docker-compose
        -f /cameras/fwc/cam1/docker-compose.yml
        --profile "${SW_OR_HW}"
        up