version: '3'

volumes:
  axds-amsdata:
    external: true

services:
  dash-hls-http:
    image: halverneus/static-file-server:latest
    ports:
      - "8080:8080"
    environment:
      FOLDER: /var/lib/amsdata
      SHOW_LISTING: "true"
      CORS: "true"
    volumes:
      - "axds-amsdata:/var/lib/amsdata:ro"
